### ISSUE TITLE
Implement a Classification Phase to Classify a Given Email

### ISSUE THREAD

**Issue by tobrien** [tobrien/crudzap#2]
Here's a YAML file with a proposed taxonomy, let's figure out the fastest way to get an email data set aligned with this taxonomy that appears to be a good starting point for what could turn into a configurable set of categories. 

```
email_taxonomy:
  family_and_personal_life:
    family_coordination:
      - event_planning
      - childcare_school_coordination
      - household_management
    personal_finance:
      - bills_statements
      - taxes
      - budgeting
    health_and_medical:
      - medical_appointments
      - health_communications
      - insurance_documents
    travel_and_recreation:
      - bookings_reservations
      - trip_planning
      - event_tickets
    social_and_friends:
      - casual_conversations
      - invitations
      - updates

  work_and_professional:
    direct_work_communication:
      - colleagues_clients
      - tasks_projects
      - deadlines_deliverables
    career_and_networking:
      - job_inquiries_opportunities
      - professional_networking
    professional_development:
      - courses_training
      - certifications
    financial_administrative:
      - payroll_expenses
      - tax_documents

  transactional_and_notifications:
    orders_purchases:
      - receipts_invoices
      - shipping_notifications
    service_subscriptions:
      - account_notices
      - renewal_reminders
    security_account_management:
      - password_resets
      - security_alerts
      - two_factor_authentication

  marketing_and_promotions:
    - retail_promotions
    - newsletters_updates
    - events_offers

  important_and_urgent:
    - time_sensitive
    - requires_immediate_attention

  spam_and_junk:
    - unsolicited_emails
    - harmful_irrelevant
```
